[package]
name = "ff7-viewer"
description = """
A model viewer for the PC version of Final Fantasy 7. Accepts an LGP archive as input.
"""
version = "0.1.0"
edition = "2021"

[workspace]
# members = [ "crates/" ]
