[package]
name = "project"
description = "Final project for COIS-4480H"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
wasm-bindgen = "0.2.83"
wee_alloc = "0.4.5"
console_error_panic_hook = "0.1.7"

[dependencies.web-sys]
version = "0.3.60"
features = [ "console" ]

[dependencies.js-sys]
version = "0.3.60"
